version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
clone_depth: 1

platform: x64
configuration:
- Debug

build:
  project: grapheme_cluster_iterator.sln
  verbosity: minimal
